### PR TITLE
adding full css

### PR DESCRIPTION
**Pull request by joebrew**
https://trello.com/c/aoW9bKtg/299-youthrex-app-increase-font-size-across-app

@xingcbrew I added the css file which you sent via trello, but it wasn't working correctly. I think that this is because the underlying html/css for the dashboard template we use has irregularly named objects. So, I found that underlying css and added it here. Now, changing things here indeed makes changes.

Here's what I suggest we do from here.

- @benmbrew zips up his `steppingup` folder and gives it to you. 
- You unzip it on your hard drive.
- You check out this branch.
- You make modifications to the css which I have placed on this branch.
- You then push back to this branch (PR already opened) and ping me.

### CODE REVIEW

**Comment by joebrew** [comment]
@xingcbrew I saw you increased the font size in some places. The app is working with your changes. Are you able to run locally as well (to see if the font changes fit what you had in mind)? If so, merge; if not, let me know.

**Comment by xingcbrew** [comment]
I am able to run the app locally and see changes. I just haven't been able
to find the css for some of the text I want to change still, so I'll try
again today and once I figure it out, I will merge the branch.

**Comment by joebrew** [comment]
@xingcbrew Understood. In your court. If you are unable to figure it out, kick back to me and I'll try to figure it out.

**Comment by xingcbrew** [comment]
@joebrew I figured out how to increase the font size in the custom.css file. However, when I committed my changes, my own R script (unrelated to this change) were also committed in the .Rhistory file and I don't know how to reverse or undo that. Please advise. Thanks!

**Comment by joebrew** [comment]
@xingcbrew The most simple way to undo this would be to run `git rm .Rhistory`, then commit and push your changes.

**Comment by joebrew** [comment]
@xingcbrew Hell yeah! You figured it out. Well done. Font looks big to me now. If you're ready, I'm DTM on this.

**Pull request merged**
