### PR TITLE
Feature/355 get 2016 ivt files and read into app

### PR DESCRIPTION
**Pull request by benmbrew**

### CODE REVIEW

**Comment by joebrew** [comment]
@benmbrew I run without any errors, but I don't see *any* 2016 data in the app. I'll post a video to the trello card.

**Comment by benmbrew** [comment]
Sorry, that's my fault. you don't have the 2016 data locally - I'll send
you directions to get it from drive asap. Then you can run everything

**Comment by joebrew** [comment]
Okay, send to me but also update documentation.

**Comment by joebrew** [comment]
@benmbrew DTM.

**Pull request merged**
